language: go

before_install:
  - make v3-generate
  - make fmt
  - make import
  - cd okta/v3
  - mv go.mod go.sum ../../
  - cd ../../

jobs:
  include:
    - stage: test_go_1.18
      go: 1.18.x
      script:
        - go mod download
        # - go test ./...
        - make v3-test
    # FIXME travis_setup_go starting failing on gimme fetching golang tip, this is upstream, nothing that we control
    # - stage: test_go_tip
    #   go: tip
    #   script:
    #     - go mod download
    #     - go test ./...
