language: go

before_install:
  - nvm install 16.16.0
  - nvm use 16.16.0
  - npm install @openapitools/openapi-generator-cli -g
  - openapi-generator-cli version-manager set 6.0.1
  - npx @openapitools/openapi-generator-cli generate -c ./.generator/config.yaml -i ./okta-management-APIs-oasv3.yaml
  - make fmt
  - make import
  - cd okta/v3

jobs:
  include:
    - stage: test_go_1.18
      go: 1.18.x
      script:
        - go mod download
        - go test ./...
    # FIXME travis_setup_go starting failing on gimme fetching golang tip, this is upstream, nothing that we control
    # - stage: test_go_tip
    #   go: tip
    #   script:
    #     - go mod download
    #     - go test ./...
