# This GitHub action can publish assets for release when a tag is created.
# Currently its setup to run on any tag that matches the pattern "v*" (ie. v0.1.0).
#
# This uses an action (hashicorp/ghaction-import-gpg) that assumes you set your
# private key in the `GPG_PRIVATE_KEY` secret and passphrase in the `PASSPHRASE`
# secret. If you would rather own your own GPG handling, please fork this action
# or use an alternative one for key handling.
#
# You will need to pass the `--batch` flag to `gpg` in your signing step
# in `goreleaser` to indicate this is being used in a non-interactive mode.
#
name: release
on:
  push:
    branches: [ okta-oas3 ]
    tags:
      - 'v*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2.4.0
      -
        name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - 
        name: Install openapi generator
        run: npm install @openapitools/openapi-generator-cli -g
      - name: Set openapi generator version
        run: openapi-generator-cli version-manager set 6.0.1 
      - name: Generate go client
        run: make v3-generate
      - 
        name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - run: make fmt
      - run: make import
      - run: cd okta/v3 && mv go.mod go.sum ../../
      - run: ls
      - run: git diff
      - 
        name: Unshallow
        run: git fetch --prune --unshallow
      - 
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.8.1
        with:
          version: latest
          args: release --rm-dist --skip-validate
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          # GitHub sets this automatically
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

